'use strict';
const test=require('node:test'),assert=require('node:assert/strict');const d=require('../src/discovery.js');const {chromium}=require('playwright');
const html='<html><body><div id="post-container"></div></body></html>';
async function fixture(t){const b=await chromium.launch({headless:true,executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE});t.after(()=>b.close());const p=await b.newPage();await p.goto('data:text/html,'+encodeURIComponent(html));return p;}
async function add(p,id){await p.evaluate(id=>{document.querySelector('#post-container').innerHTML='<div class="post-card"><span data-id="'+id+'"></span><img class="post-image" data-type="image"><a class="content-download-btn" href="https://instacognito.com/media?id='+id+'"></a></div>';},id);}
test('capture initial install and idempotent reinstall preserve observer, queue, generation and one listener',async t=>{const p=await fixture(t);const n=p.listenerCount('framenavigated');await d.installCapture(p);await d.resetCapture(p,'posts');await p.evaluate(()=>window.savedObserver=window.__ffCapture.observer);await add(p,'A');const before=await p.evaluate(()=>({generation:window.__ffCapture.generation,queued:window.__ffCapture.queue.length}));await Promise.all([d.installCapture(p),d.installCapture(p)]);assert.equal(await p.evaluate(()=>window.savedObserver===window.__ffCapture.observer),true);assert.deepEqual(await p.evaluate(()=>({generation:window.__ffCapture.generation,queued:window.__ffCapture.queue.length})),before);assert.equal(p.listenerCount('framenavigated'),n+1);const got=await d.drainCapture(p);assert.ok(got.batches.some(b=>b.cards.some(c=>c.shortcode==='A')));});
test('same Page main navigation creates a new document capture and drain works without explicit reset',async t=>{const p=await fixture(t);await d.installCapture(p);await add(p,'OLD');await d.drainCapture(p);await p.goto('data:text/html,'+encodeURIComponent(html+'<!--new-->'));await d.drainCapture(p);await add(p,'NEW');const got=await d.drainCapture(p);assert.ok(got.batches.some(b=>b.cards.some(c=>c.shortcode==='NEW')));assert.ok(!got.batches.some(b=>b.cards.some(c=>c.shortcode==='OLD')));});
test('same Page reload restores capture via reset directly, not only install',async t=>{const p=await fixture(t);await d.installCapture(p);await p.reload();await d.resetCapture(p,'reels');await add(p,'B');const got=await d.drainCapture(p);assert.equal(got.batches[0].category,'reels');assert.equal(p.listenerCount('framenavigated'),1);});
test('subframe navigation neither replaces nor invalidates main capture',async t=>{const p=await fixture(t);await d.installCapture(p);await p.evaluate(()=>{window.saved=window.__ffCapture;const frame=document.createElement('iframe');frame.name='child';document.body.append(frame);});const frame=p.frames().find(f=>f!==p.mainFrame());await frame.goto('data:text/html,child');await d.installCapture(p);assert.equal(await p.evaluate(()=>window.saved===window.__ffCapture),true);await p.evaluate(()=>delete window.__ffCapture);await frame.goto('data:text/html,child2');await assert.rejects(d.drainCapture(p),{code:'OBSERVATION_GAP'});});
test('capture loss or malformed state within a document fails closed',async t=>{const p=await fixture(t);await d.installCapture(p);await p.evaluate(()=>delete window.__ffCapture);await assert.rejects(d.resetCapture(p,'posts'),{code:'OBSERVATION_GAP'});await p.reload();await d.installCapture(p);await p.evaluate(()=>window.__ffCapture.reset=null);await assert.rejects(d.installCapture(p),{code:'OBSERVATION_GAP'});});
test('closed Page evaluation error is not translated into empty successful observation',async t=>{const p=await fixture(t);await d.installCapture(p);await p.close();await assert.rejects(d.drainCapture(p));});
test('generation overflow remains latched across idempotent installs and drains',async t=>{const p=await fixture(t);await d.installCapture(p);await p.evaluate(()=>{window.__ffCapture.gap='generation-buffer-overflow';});await d.installCapture(p);const got=await d.drainCapture(p);assert.equal(got.gap,'generation-buffer-overflow');});
test('synthetic adapter without event API keeps explicit poll fallback without evaluate',async()=>{const p={evaluate(){throw Error('must not evaluate synthetic fallback');}};assert.equal(await d.installCapture(p),false);await d.resetCapture(p,'posts');assert.deepEqual(await d.drainCapture(p),{batches:[],generation:0,gap:null});});

test('same-document hash navigation preserves queued generations',async t=>{const p=await fixture(t);await d.installCapture(p);await add(p,'SAVED');await p.evaluate(()=>{window.saved=window.__ffCapture;location.hash='same-document';});await d.installCapture(p);assert.equal(await p.evaluate(()=>window.saved===window.__ffCapture),true);const got=await d.drainCapture(p);assert.ok(got.batches.some(b=>b.cards.some(c=>c.shortcode==='SAVED')));});
test('acknowledged discovery ledger survives Page reload and subsequent new-document capture',async t=>{const p=await fixture(t);const fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path'),lib=require('../src/index.js');const dir=await fs.mkdtemp(path.join(os.tmpdir(),'ff-reload-ledger-'));t.after(()=>fs.rm(dir,{recursive:true,force:true}));const file=path.join(dir,'discovery.jsonl');const ledger=await d.openLedger(file,{handle:'example',runId:'offline',runtime:{}});try{await d.installCapture(p);await d.resetCapture(p,'posts');await add(p,'OLD');let capture=await d.drainCapture(p);await ledger.checkpoint({items:lib.normalizeItems(capture.batches.flatMap(b=>b.cards),{category:'posts'}).items,frontier:{category:'posts',pages:20,elapsedMs:1000}});await p.reload();await d.resetCapture(p,'posts');await add(p,'NEW');capture=await d.drainCapture(p);await ledger.checkpoint({items:lib.normalizeItems(capture.batches.flatMap(b=>b.cards),{category:'posts'}).items,frontier:{category:'posts',pages:1,elapsedMs:100}});assert.deepEqual([...ledger.observed.values()].map(i=>i.rawPostId).sort(),['NEW','OLD']);assert.equal(ledger.frontier.posts.pages,20);}finally{await ledger.close('offline-done');}const reopened=await d.openLedger(file,{handle:'example',runId:'readback',runtime:{}});try{assert.deepEqual([...reopened.observed.values()].map(i=>i.rawPostId).sort(),['NEW','OLD']);assert.equal(reopened.frontier.posts.pages,20);}finally{await reopened.close('verified');}});
